#pragma once

#include "SoundObject.hpp"
#include "Undenormal.hpp"
#include "StdNoise.hpp"

#include "ArrayMatrix.hpp"
#include "ArrayVector.hpp"
#include "AudioFFT.h"
#include "FFTConvolver.h"

#include "gnuplot.hpp"

#include "Integrators.hpp"
#include "LaguerrePolynomialRoots.hpp"
#include "libnyquist.hpp"
#include "LinearInterpolator.h"
#include "LinearRegression.hpp"
#include "LinearSine.h"
#include "LogisticRegression.hpp"
#include "LuaJIT.hpp"
#include "MusicFunctions.hpp"
#include "PolynomialRoots.hpp"
#include "SamplerateCalculus.hpp"

/*
#include "Filters.h"
#include "Iir.h"
#include "fo_apf.h"
#include "fo_hpf.h"
#include "fo_lpf.h"
#include "fo_shelving_high.h"
#include "fo_shelving_low.h"
#include "so_apf.h"
#include "so_bpf.h"
#include "so_bsf.h"
#include "so_butterworth_bpf.h"
#include "so_butterworth_bsf.h"
#include "so_butterworth_hpf.h"
#include "so_butterworth_lpf.h"
#include "so_hpf.h"
#include "so_linkwitz_riley_hpf.h"
#include "so_linkwitz_riley_lpf.h"
#include "so_lpf.h"
#include "so_parametric_cq_boost.h"
#include "so_parametric_cq_cut.h"
#include "so_parametric_ncq.h"
*/