require('dspfilters')
require('sndfile')
--require('stdsamples')
snd = sndfile.SndFileReaderFloat("../../Data/baby.wav")
wav = dspfilters.float_vector(snd:size())
snd:read(wav:size(),wav:data())
filt= dspfilters.ButterworthLowPassFilter(4,1000,snd:samplerate())
filt:ProcessBlock(wav:size(),wav:data(),wav:data())
out = sndfile.SndFileWriterFloat("test.wav",0x10006,snd:channels(),snd:samplerate())
out:write(wav:size(),wav:data())
