require('dspfilters')
require('kfr2')
require('sndfile')
--require('stdsamples')
snd = sndfile.SndFileReaderFloat("../../Data/baby.wav")
wav = dspfilters.float_vector(snd:size())
filt= dspfilters.ButterworthLowPassFilterQ(4,400,snd:samplerate())
filt:ProcessBlock(wav:size(),wav:data(),wav:data())
out = sndfile.SndFileWriterFloat("test.wav",0x10006,snd:channels(),snd:samplerate())
out:write(wav:size(),wav:data())kfr2.wav_save(wav,"test.wav",fmt.channels, fmt.samplerate)
